### ISSUE TITLE
Small typo on question in Data Structures Quiz

### ISSUE THREAD

**Issue by jacoblogan98** [learn-co-curriculum/python-p3-quiz-data-structures#1]
### Canvas Link

https://learning.flatironschool.com/courses/6049/quizzes/38385?module_item_id=489441

### Concern

On the question relating to using a for loop on the 'lunch_menu' list, the answers have 'lunch_item' as the list name instead. It isn't letting me attach an image, so here's a link where you can view the typo:

https://flatiron-staff.slack.com/archives/C03MK7965K4/p1674013639965019

**Comment by professor-ben** [comment]
@pgill97 I fixed this manually in Canvas, but I'm having trouble finding the correct repo for the quiz. Would you mind fixing this when you get the chance?

-Ben
