### ISSUE TITLE
Some questions were not related to Python data structure 

### ISSUE THREAD

**Issue by sbasken** [learn-co-curriculum/python-p3-quiz-data-structures#2]
### Canvas Link

https://learning.flatironschool.com/courses/6266/quizzes/44825/take/questions/305692

### Concern

Q5 was about JavaScript and not about Python.

**Comment by pgill97** [comment]
I think this is okay since this is more of a big O question and the students have learned JS in previous phases. @professor-ben  Thoughts? It was like this in the Ruby curriculum. I can change it if it would be better.

**Comment by professor-ben** [comment]
@pgill97 I like the idea of connecting concepts between languages, but this module focuses more on Python-specific structures than general ideas. This question would be appropriate in DSA, but I think changing it to Python here would be best.

**Comment by pgill97** [comment]
Changed question to use python code.
