### ISSUE TITLE
Questions on Topics Not Covered in Lessons/Labs

### ISSUE THREAD

**Issue by connork97** [learn-co-curriculum/python-p3-quiz-data-structures#3]
### Canvas Link

https://learning.flatironschool.com/courses/6274/quizzes/45932?module_item_id=554050

### Concern

Questions three and five (in my test at least, assuming they don't rotate) were about algorithms and Big O Notation.  They were entirely unfamiliar to me until the Data Structures quiz asked about them, and when I double checked each lesson and lab those words never appeared.

### Suggested Changes

I would add these topics to the lessons where applicable, even if brief, or take it out of the quiz since it's not taught.  Unless it is to give us an idea before covering it going forward I don't see why quiz questions were never mentioned.

**Comment by pgill97** [comment]
Removed question from quiz.
