### ISSUE TITLE
Quiz Questions Don't Match Subject

### ISSUE THREAD

**Issue by developerjaym** [learn-co-curriculum/python-p3-quiz-data-structures#5]
### Canvas Link

https://my.learn.co/courses/653/quizzes/7002?module_item_id=83652

### Concern

The quiz questions cover git and JavaScript and Big O, but those aren't in this phase of the curriculum.
I also read the MD files in this repo and one mentions Active Record, too.

### Suggested Changes

I think the questions need to be reworked for what is currently in Python Phase 3.

**Comment by lizbur10** [comment]
Hi @developerjaym! Thanks for bringing this to our attention. This quiz was a placeholder that mistakenly wound up in the curriculum. We have removed it from Canvas until the real quiz is ready to be deployed. 💙
