### ISSUE TITLE
Quiz Is NOT Relevant

### ISSUE THREAD

**Issue by ckelly38** [learn-co-curriculum/python-p3-quiz-data-structures#6]
### Canvas Link

https://learning.flatironschool.com/courses/6559/quizzes/47503?module_item_id=571499

### Concern

I saw that we learned about Python. The quiz questions were **not** about that at all. In fact the quiz questions were on different older stuff. Which was not really fair to ask.

### Suggested Changes

Design a different quiz here for the Phase 3 Data Structures. It should be about those Data Structures we learned in Python.

**Comment by lizbur10** [comment]
Hi @ckelly38 ! Thanks for bringing this to our attention. This quiz was a placeholder that mistakenly wound up in the curriculum. We have removed it from Canvas until the real quiz is ready to be deployed. 💙
